# type: ignore
import sys
from typing import Literal, List, Any, Optional, Tuple
import numpy as np
import enum
import numpy

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:srcml_cpp_caller.h>    ####################


def to_cpp(
    xml_str: str,
    encoding_src: str = "utf-8",
    encoding_xml: str = "utf-8"
    ) -> Optional[str]:
    pass


def to_srcml(
    cpp_code: str,
    include_positions: bool = True,
    encoding_src: str = "utf-8",
    encoding_xml: str = "utf-8"
    ) -> Optional[str]:
    pass
####################    </generated_from:srcml_cpp_caller.h>    ####################

# </litgen_stub>
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
